### ISSUE TITLE
Enhancement: Add current timeline of merge progress on the site with milestones crossed off as completed

### ISSUE THREAD

**Issue by MiConnell** [InsideTheSim/ethmerge.com-content#56]
Now that the [merger devnet has successfully completed](https://www.trustnodes.com/2021/05/01/ethereum-2-0-merger-devnet-completes-successfully) (but as [vitalik pointed out](https://www.reddit.com/r/ethereum/comments/n2jq9o/ethereum_20_merger_devnet_completes_successfully/gwjr0yz/) this is only a test chain that's post-merge from genesis, not a full test of the actual transition) it would be great to use ethmerge as a living document of the progress of the merge.

Something like:
## steps to complete the merge successfully
- [x] rough devnet
- [ ] longer new devnets
- [ ] public testnet
- [ ] months long testnet replicating the live network with fake eth
- [ ] merger (RIP miners)
## there are three major phases involved:
- [x] Phase 0: launch the [beacon chain](https://ethereum.org/en/eth2/beacon-chain/)
- [ ] Phase 1: launch [shard chains](https://ethereum.org/en/eth2/shard-chains/)
- [ ] Phase 2: complete [the merge](https://ethereum.org/en/eth2/docking/) 🎉
